### PR TITLE
Correct comparison operator to enable support for multiple vmk nics

### PR DESCRIPTION
**Pull request by dwoolger**

### CODE REVIEW

**Comment by gjngeldenhuis** [comment]
This seems like a really small change that could be easily merged? Any takers at Dell?

**Comment by gavin-scott** [comment]
Seems like this should probably be issued against upstream. @dwoolger did you intend to push this to https://github.com/vmware/vmware-vcenter ?

**Comment by gjngeldenhuis** [comment]
We (Skyscape) are happy to issue against upstream but upstream and Dell has diverged quite a lot and not sure upstream is as active as they used to be. The same request is currently with upstream.

**Comment by gavin-scott** [comment]
Definitely true that it's diverged a lot :-(

Change looks correct so we'll get it in here.

**Comment by gjngeldenhuis** [comment]
Thanks! @gavin-scott would you mind sending me a pm on twitter @ggeldenhuis with some contact details? I would love to discuss the possibility of closer collaboration on this and related modules. We have some scope and the will to improve things and would love to collaborate. We are trying to goad vmware into action to get upstream, dell and skyscape forks all on the same page again.

**Pull request merged**
