### PR TITLE
Code cleanup: Puppet logs for esx software update to follow new code convention

### PR DESCRIPTION
**Pull request by kaushalgala**
Changing strings in accordance with the style for new code to follow %s way of strings

Also added some timestamps for some of the strings, since Puppet logging
does not do timestamps.

### CODE REVIEW

**Comment by kaushalgala** [comment]
@gavin-scott  did some string cleanups. Not sure which Jira to attach to.  Did some end-end update tests with this PR and seems fine.

**Comment by kaushalgala** [comment]
@ripienaar will be happy with this changes, i assume :)

**Comment by ripienaar** [comment]
very nice, thank you :)

**Comment by ripienaar** [comment]
Looks good to me, I am not sure how we are for timing around releases but I think it's good to merge now, @gavin-scott ?

**Comment by kaushalgala** [comment]
Talked with @gavin-scott  offline, we will put this in 8.3.1 timeframe

**Comment by gavin-scott** [comment]
I'd like to hold this until we branch for 8.3.1 Changes look good but most of this code isn't unit tested and I don't think we can be guaranteed there's not some kind of syntax error hiding in these changes.

**Comment by kaushalgala** [comment]
@gavin-scott  I can see your point and its ok if this gets merged later. However, as you can see from the code changes, we can be assured there is no syntax error hiding :).  I tested the changes with actual software update workflow which covers all the workflow except the uninstall part. The uninstall part was tested by a test manifest.

btw, I noticed we don't have Travis CI integration for the unit tests for vmware-vcenter project. Any plans in future to have that ?

**Comment by gavin-scott** [comment]
We're at the stage of 8.3 where we should only be merging stop-ship fixes.

I thought Travis CI was on this. I turned it on now, if you push an update to this branch we can see if it kicks off the tests.

**Comment by kaushalgala** [comment]
Is there a way to manually kick off Travis CI on desired PR, or even a commit ?  That way a developer can do a pre-checkin test before submitting a PR  :)

**Comment by gavin-scott** [comment]
I think if you force push to this branch it will kick it off

**Comment by kaushalgala** [comment]
That I know :) I was trying to see if we can do it from the github UI itself.

**Comment by gavin-scott** [comment]
You can once it starts running tests for a PR. At that point there will be a link on the PR to Travis CI and you can start new ones. But right now Travis CI doesn't know about the PR -- it should be waiting now for new PRs or commits to run the tests.

**Comment by kaushalgala** [comment]
@gavin-scott closing this PR for now since I may need to do any fixes for updates, and that would stale this PR. I will re-submit a new one for this cleanup once the branch is open for 8.3.1 / 8.4 changes.

**Pull request closed without merging**
