### PR TITLE
ASM-9275 Better handling of VIM connection close

### PR DESCRIPTION
**Pull request by kaushalgala**
Seems current implementation of vim.close does not logout session gracefully, rather results in a
ManagedObjectNotFound exception and gets ignored silently. To fix this, we override the base 
implementation to do appropriate logout operation, and then do the original implementation.

### CODE REVIEW

**Comment by kaushalgala** [comment]
@gavin-scott @ripienaar changes for vmware module based on discussions in https://github.com/dell-asm/asm-deployer/pull/2077

**Comment by gavin-scott** [comment]
Looks good to me. Can you review also @ripienaar ?

**Comment by ripienaar** [comment]
look good, I filed https://github.com/vmware/rbvmomi/issues/101 please mention it in the comment so we know when we can drop this patch

**Comment by kaushalgala** [comment]
Thanks @ripienaar for filing the bug. I've updated this PR with your suggestion, ready to merge

**Pull request merged**
