### PR TITLE
ASM-6603 Support vSAN read Nodes with FX2 All-flash platforms

### PR DESCRIPTION
**Pull request by sushilrai**
In case there is only SSD disk on the server, then we will create AllFlsh type of DiskGroup else Hybrid DiskGroup will be created.

### CODE REVIEW

**Comment by sushilrai** [comment]
DO NOT MERGE. Needs to be tested with correct hardware

**Comment by gavin-scott** [comment]
:+1:

**Comment by ripienaar** [comment]
is this now good to merge @sushilrai, done testing? I dont know this code at all but based on @gavin-scott 's 👍  I guess its good

**Comment by sushilrai** [comment]
https://github.com/gavin-scott Please review. QA Team is waiting for the VSAN all flash feature for testing

**Pull request merged**
