### PR TITLE
ASM-9312 Flattens the array to loop over all the hosts

### PR DESCRIPTION
**Pull request by arunrordell**

### CODE REVIEW

**Comment by kaushalgala** [comment]
@arunrordell might be nice to have background of the problem, which would also explain why we need to flatten ?

**Comment by gavin-scott** [comment]
@kaushalgala rather non-intuitively the `child.host` parameter is an array of hosts. I guess ` datacenter.hostFolder.children` is a tree actually. So the children have to be flattened to get a single array of objects.

**Comment by gavin-scott** [comment]
@kaushalgala I'm good with this as is -- did you want any updates to the commit message?

**Comment by kaushalgala** [comment]
@gavin-scott what you explains makes sense. It might be nice to add a quick comment in the code where we do the flatten.

**Pull request merged**
