### PR TITLE
Find VM search needs update

### PR DESCRIPTION
**Pull request by sushilrai**
FindVM method was failing to find the VMs available in the datacenter. Recursion logic was not correct. Pulled the updated functionality from the upstream vmware-vcenter puppet module

### CODE REVIEW

**Comment by sushilrai** [comment]
@gavin-scott please review

**Comment by gavin-scott** [comment]
@sushilrai this breaks the changes that were put in for ASM-9516 #191 That issue was that source VMs used for cloning VMs were getting powered on when we create the clone VM. What failure were you seeing with the current code?

**Comment by sushilrai** [comment]
Search was not working. VM Template was present in the datacenter but due to the changes included in #191 search was continued even if the VM was found. 

For example datacenter has Template1, Template2, Template3, and we are searching for Template1. With current logic search will find Template1 but will continue the loop for all the templates in the datacenter. last template 'Template3' do not matches the requested template and returns `nil`

**Comment by gavin-scott** [comment]
@sushilrai if you send me the vcenter and template you're searching for I'll try to fix it without adding back in the `@vm_obj` caching back in.

**Comment by gavin-scott** [comment]
@sushilrai I'm going to close this, I know #191 fixed some subtle problems with clone vm use cases. If you see a template that exhibits this problem again let me know and we can look at it again.

**Pull request closed without merging**
